### PR TITLE
fix: many incorrect pointer equality comparisons

### LINKED ISSUE #1017: Missing data from `miner_fee_debt` at epoch `1957803`
### Describe the bug:

Expecting data from SP `f07830` when running task `miner_fee_debt` at epoch `1957803`. When running this task focused on this epoch, the output does not include this miner's record.

We can confirm the extractor is executing where lily detects the state diff for this SP.

We expect data at this height for this SP due to data presence from Lily v0.10.1 in production.

### Steps to Reproduce:

1. Run lily v0.11.0 w state that includes epoch `1957803`.
2. Execute `lily job run --tasks="miner_fee_debt" --storage="File1" index height --height=1957803` with storage configured for writing CSVs:

```
        [Storage.File.File1]
          Format = "CSV"
          Path = "/var/lib/lily/"
          OmitHeader = false
          FilePattern = "{table}.csv"
```
3. Observe missing records with `cat /var/lib/lily/miner_fee_debt.csv | grep f07830`.

### PR DESCRIPTION
**Pull request by frrist**
fixes #1017 

- the hardest of facepalms

### CODE REVIEW

File: tasks/actorstate/miner/context.go [hunk 1]
```diff
@@ -49,23 +50,25 @@ func NewMinerStateExtractionContext(ctx context.Context, a actorstate.ActorInfo,
...
 	PrevState miner.State
 	PrevTs    *types.TipSet
 
-	CurrActor *types.Actor
-	CurrState miner.State
-	CurrTs    *types.TipSet
+	CurrActor     *types.Actor
+	CurrState     miner.State
+	CurrTs        *types.TipSet
+	PreviousState bool
```
Comment (placer14) [inline tasks/actorstate/miner/context.go:69]: nit: A slightly more expressive name:
```suggestion
	PreviousStateExists bool
```

File: tasks/actorstate/miner/deadline_info.go [hunk 2]
```diff
@@ -36,7 +36,9 @@ func (DeadlineInfoExtractor) Extract(ctx context.Context, a actorstate.ActorInfo
 		if err != nil {
 			return nil, err
 		}
-		if prevDeadlineInfo == currDeadlineInfo {
+		// TODO implement equality function
+		// dereference pointers to check equality
+		if *prevDeadlineInfo == *currDeadlineInfo {
```
Comment (placer14) [inline tasks/actorstate/miner/deadline_info.go:41]: This is brittle. We have to be sure that `err == nil` guarantees we're protected from a nil-deref panic here and forever into the future. How is that being guaranteed? I would prefer this check is explicit here instead of expecting it inside the caller. If we have a local equality function doing that, that could work just a well.

Comment (placer14) [inline tasks/actorstate/miner/deadline_info.go:41]: This is brittle. We have to be sure that `err == nil` guarantees we're protected from a nil-deref panic here and forever into the future. How is that being guaranteed? I would prefer this check is explicit here instead of expecting it inside the caller. If we have a local equality function doing that, that could work just a well.

```suggestion
		if prevDeadlineInfo != nil &&
		   currDeadlineInfo != nil &&
		   *prevDeadlineInfo == *currDeadlineInfo {
```

File: tasks/actorstate/miner/locked_funds.go [hunk 3]
```diff
@@ -36,7 +36,11 @@ func (LockedFundsExtractor) Extract(ctx context.Context, a actorstate.ActorInfo,
 		if err != nil {
 			return nil, fmt.Errorf("loading previous miner locked funds: %w", err)
 		}
-		if prevLocked == currLocked {
+
+		// if all values are equal there is no change.
+		if prevLocked.VestingFunds.Equals(currLocked.VestingFunds) &&
+			prevLocked.PreCommitDeposits.Equals(currLocked.PreCommitDeposits) &&
+			prevLocked.InitialPledgeRequirement.Equals(currLocked.InitialPledgeRequirement) {
```
Comment (placer14) [inline tasks/actorstate/miner/locked_funds.go:43]: Protect against nil-deref panic here?

File: tasks/actorstate/multisig/multisig.go [hunk 4]
```diff
@@ -119,11 +119,12 @@ type MsigExtractionContext struct {
 	CurrState multisig.State
 	CurrTs    *types.TipSet
 
-	Store adt.Store
+	Store         adt.Store
+	PreviousState bool
```
Comment (placer14) [inline tasks/actorstate/multisig/multisig.go:123]: nit:
```suggestion
	PreviousStateExists bool
```

File: tasks/actorstate/verifreg/verifreg.go [hunk 5]
```diff
@@ -20,11 +20,12 @@ type VerifiedRegistryExtractionContext struct {
 	PrevState, CurrState verifreg.State
 	PrevTs, CurrTs       *types.TipSet
 
-	Store adt.Store
+	Store         adt.Store
+	PreviousState bool
```
Comment (placer14) [inline tasks/actorstate/verifreg/verifreg.go:24]: nit:
```suggestion
	HasPreviousState bool
```

**Review by placer14 — APPROVED** [review]
Some nits for safety and clarity. Otherwise, LGTM

File: tasks/actorstate/miner/locked_funds.go (hunk 3 above)
Comment (frrist) [reply tasks/actorstate/miner/locked_funds.go:43]: the `LockedFunds` type isn't a pointer, nor are its fields so we can safely use them here.

File: tasks/actorstate/miner/deadline_info.go (hunk 2 above)
Comment (frrist) [reply tasks/actorstate/miner/deadline_info.go:41]: Since we know the miner has state we can safely assume it has non-nil deadline information. (the method that creates deadline info will never return null: https://github.com/filecoin-project/specs-actors/blob/v8.0.1/actors/builtin/miner/deadlines.go#L15
