### PR TITLE
fix: avoid reporting processing error for malformed messages

### LINKED ISSUE #660: Processing error: unknown parameters for b
### Describe the bug:

messages task sometimes fails with the error `failed to parse message params: unknown parameters for b`

### Steps to Reproduce:

Examples from logs

956422,bafy2bzacec4i3dwswste5yiet5a6ihiznzdcsekw46xstmlr3iew5ynuxipbw,visor,messages,2021-07-25T02:53:39.601Z,2021-07-25T02:53:39.633Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceamxxkg3lpba7w5k3yufklizf5kixryhrzgjpg3udscqmplft4jqo""},""Error"":""failed to parse message params: unknown parameters for b""}]"

994599,bafy2bzaceb4qrhwsz3pduqsfgmcsvkbzcv3zqbwnpxseeikdpkozl7vitkj5g,visor,messages,2021-08-09T20:19:34.975Z,2021-08-09T20:19:35.002Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaced4ystr2243xfi6zow4iscuc74l4addtkx67ojgc7kyajoy56fooo""},""Error"":""failed to parse message params: unknown parameters for b""}]"

994594,bafy2bzaceb6np2v6mlw3gmddnfutg4emd2f5vhlv5vci3mowjiyv76sicwta2,visor,messages,2021-08-09T20:21:26.279Z,2021-08-09T20:21:26.309Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceb54a6mnwequyjyv3alej6vvnsiggsnmo45ykqgax5vnm2hgi26zm""},""Error"":""failed to parse message params: unknown parameters for b""}]"

### LINKED ISSUE #667: Processing error: BeginMap called on a types.Link
### Describe the bug:

messages task sometimes fails with error: `failed to parse message params: cbor decode into InitExecParams (bafkqactgnfwc6nbpnfxgs5a.2) failed: func called on wrong kind: BeginMap called on a types.Link node (kind: link), but only makes sense on map`

### Steps to Reproduce:

Examples from logs:

784616,bafy2bzacec5ivbqayq7jzprk6a2oqdyo7u65oagnjv4ercfy7apaqrkp7jxv6,visor,messages,2021-06-19T22:49:46.778Z,2021-06-19T22:49:54.027Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceaubtkxigzl2pbhxc2rpvdprcfgg3b66gk7g5wzttxtmjfuy7lpq6""},""Error"":""failed to parse message params: cbor decode into InitExecParams (bafkqactgnfwc6nbpnfxgs5a.2) failed: func called on wrong kind: BeginMap called on a types.Link node (kind: link), but only makes sense on map""}]"
784575,bafy2bzaceds7hwbjsmizwmdhqgikfyp3lm5j6lb6opqpbl5qc4abvhrvnv7p6,visor,messages,2021-06-19T23:03:02.903Z,2021-06-19T23:03:09.341Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacec2r6gefwmlj22usmiflnog3ebxjlm4zqxwoh4fdxcd7kcgyaexzi""},""Error"":""failed to parse message params: cbor decode into InitExecParams (bafkqactgnfwc6nbpnfxgs5a.2) failed: func called on wrong kind: BeginMap called on a types.Link node (kind: link), but only makes sense on map""}]"
784571,bafy2bzacedhd6xfimi7osvormslyyxud3b6f2zjclw2x6xlspmdlb5xbit54u,visor,messages,2021-06-19T23:04:20.916Z,2021-06-19T23:04:27.897Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacebtjveolnccmbnzweuxkekgwuqwdensofpe3dfdffarxqobe5ubju""},""Error"":""failed to parse message params: cbor decode into InitExecParams (bafkqactgnfwc6nbpnfxgs5a.2) failed: func called on wrong kind: BeginMap called on a types.Link node (kind: link), but only makes sense on map""}]"
784528,bafy2bzacec4pnmhzqjyooo2lyvy6kva4a2ugykboqn3utaa5hme7h7iwgsfbi,visor,messages,2021-06-19T23:17:36.7Z,2021-06-19T23:17:43.199Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaced4xe3qgpl4nq7hz323sbrmynofmx2gdu6qeez77erktn7q6q64y6""},""Error"":""failed to parse message params: cbor decode into InitExecParams (bafkqactgnfwc6nbpnfxgs5a.2) failed: func called on wrong kind: BeginMap called on a types.Link node (kind: link), but only makes sense on map""}]"

### PR DESCRIPTION
**Pull request by iand**
We were reporting all message param parsing failures as errors in the processing report. However some messages simply have invalid parameters and failed to execute in the VM. Check this by looking at the exit code of the message and ignore the failure if the vm also failed to decode the parameters.

Note: the added test doesn't cover the ignore behaviour but documents the kind of failures we have seen in the wild.

Fixes #667, #666, #665, #664, #668, #663

~Also improves the error message reported by #660 but does not fix the underlying problem.~ Updated to also fix #660 by looking for actor in current state tree if not found in next.

PR is a little noisy because I renamed ts/pts arguments to next/current for clarity.

### CODE REVIEW

File: tasks/messages/message.go [hunk 1]
```diff
@@ -232,10 +233,14 @@ func (p *Task) ProcessMessages(ctx context.Context, ts *types.TipSet, pts *types
 			}
 			parsedMessageResults = append(parsedMessageResults, pm)
 		} else {
-			errorsDetected = append(errorsDetected, &MessageError{
-				Cid:   m.Cid,
-				Error: xerrors.Errorf("failed to parse message params: %w", err).Error(),
-			})
+			if rcpt.ExitCode == int64(exitcode.ErrSerialization) {
```
Comment (iand) [inline tasks/messages/message.go:236]: This is the actual fix

File: tasks/messages/message.go [hunk 2]
```diff
@@ -278,6 +283,10 @@ func (p *Task) parseMessageParams(m *types.Message, destCode cid.Cid) (string, s
 		return "Send", "", nil
 	}
 
+	if !destCode.Defined() {
```
Comment (iand) [inline tasks/messages/message.go:286]: This is the error message improvement mentioned

File: chain/indexer.go [hunk 3]
```diff
@@ -208,6 +207,7 @@ func (t *TipSetIndexer) TipSet(ctx context.Context, ts *types.TipSet) error {
 	}
 
 	ll := log.With("current", int64(current.Height()), "next", int64(next.Height()))
+	ll.Debugw("indexing tipset")
```
Comment (frrist) [inline chain/indexer.go:210]: nit: `ll.Debug`

File: tasks/messages/message_test.go [hunk 4]
```diff
@@ -0,0 +1,141 @@
...
+func mustDecodeBase64(t *testing.T, s string) []byte {
+	t.Helper()
+	b, err := base64.StdEncoding.DecodeString(s)
+	if err != nil {
+		t.Fatalf("bad base64 data: %v", err)
+	}
+	return b
+}
+
+func TestParseMessageParams(t *testing.T) {
```
Comment (frrist) [inline tasks/messages/message_test.go:25]: :heart: :heart: :heart:

**Review by frrist — APPROVED** [review]
awesome
