### PR TITLE
fix: add index column constraint to vm_messages table

### LINKED ISSUE #1106: Duplicated rows in vm_messages task when using CSV as storage
### Describe the bug:
When running lily job run --storage CSV --task vm_messages walk --from X --to Y, the vm_messages.csv that is produced contains some duplicated rows.

### Steps to Reproduce: 

1. Initialize Lily from any snapshot and run a walk covering 200 epochs storing the results in CSVs: `lily job run --storage CSV --task vm_messages walk --from X --to Y`. I tried with `--from 100100 --to 100300` using `snapshot_97920_100802_1666950561.car.zst` available at `s3://sentinel-backfill/historical-exports/snapshot_97920_100802_1666950561.car.zst`.
2. See duplicated lines with `cat /tmp/vm_messages.csv | sort | uniq -d`.

This is the output of `2`. Every row is a duplicated found in the original CSV. 
```
height,state_root,cid,source,from,to,value,method,actor_code,exit_code,gas_used,params,returns
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedylon6kapiwufnddau6simggg7roabbdljzkx66rc3ccizixqi7o,bafy2bzaceamicuy2h55d2pwip5srxydiquj5rnginulosb7xzfch3bkqjwzke,f01235,f04,0,9,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,481415,,"{""PledgeCollateral"":{""Int"":8305121611547023530889461},""QualityAdjPower"":{""Int"":385958680480186368},""QualityAdjPowerSmoothed"":{""PositionEstimate"":{""Int"":131031567524352342715596315439041873899679366810938465141},""VelocityEstimate"":{""Int"":1338356856550395441892507665153955554806865091651389}},""RawBytePower"":{""Int"":385721185968586752}}"
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedyozj4nzichbuowjps6zcgo4grzesx7hhc36lt5boz3skpy5h5f2,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f01839,f02,0,3,bafkqaddgnfwc6mjpojsxoylsmq,0,1650891897,,"{""ThisEpochBaselinePower"":{""Int"":2900910851306909927},""ThisEpochReward"":{""Int"":63652721713844685221},""ThisEpochRewardSmoothed"":{""PositionEstimate"":{""Int"":21637810881947330599433200029828978685045752880790941636015},""VelocityEstimate"":{""Int"":91555055095056965112527863752753533663925709816534258}}}"
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedyp5vhgevnxwk5kup3e7p3bjs5q2ytfl46nrck2zibcmusffqwwu,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f01552,f04,0,4,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,1158613986,"{""EventEpoch"":100359,""Payload"":""gQE=""}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedyrshxrxc2yw6pkw5kn2r6g5wxhxahdm3ucwgew5hdcbrs2pxdhg,bafy2bzaceccf465l7rkojw5esasa56o4ftct5forogv2bmqowxnjhp74v453m,f020330,f04,0,9,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,484415,,"{""PledgeCollateral"":{""Int"":8305121611547023530889461},""QualityAdjPower"":{""Int"":385958680480186368},""QualityAdjPowerSmoothed"":{""PositionEstimate"":{""Int"":131031567524352342715596315439041873899679366810938465141},""VelocityEstimate"":{""Int"":1338356856550395441892507665153955554806865091651389}},""RawBytePower"":{""Int"":385721185968586752}}"
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedyyqbwfwq5h7wlhosziw5v2oh5sqbf7zwkfslz247ybew3rbkq66,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f04,f022010,0,12,bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza,0,41530736,"{""EventType"":1}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedyzo2hybla32tvvwygmqgx7qanspzoqau7da24rjz3t6nkbf5kt4,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f015618,f04,0,9,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,264972982,,"{""PledgeCollateral"":{""Int"":8305121611547023530889461},""QualityAdjPower"":{""Int"":385958680480186368},""QualityAdjPowerSmoothed"":{""PositionEstimate"":{""Int"":131031567524352342715596315439041873899679366810938465141},""VelocityEstimate"":{""Int"":1338356856550395441892507665153955554806865091651389}},""RawBytePower"":{""Int"":385721185968586752}}"
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedz2vh5z7ndc7x4aly5ecyz7rit5wilxiq642xkmi4uw7d5qze3nm,bafy2bzacebaodxarhjsodeuinqpwdoovtm7tf772crqtmfvlueb4piddviw7e,f05,f02,0,3,bafkqaddgnfwc6mjpojsxoylsmq,0,731157,,"{""ThisEpochBaselinePower"":{""Int"":2900910851306909927},""ThisEpochReward"":{""Int"":63652721713844685221},""ThisEpochRewardSmoothed"":{""PositionEstimate"":{""Int"":21637810881947330599433200029828978685045752880790941636015},""VelocityEstimate"":{""Int"":91555055095056965112527863752753533663925709816534258}}}"
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedz3xfnynmeohztsc4y5pswkuil73t346s6ixhot24pg3p4gr5xr2,bafy2bzacecajhlkegknppzey2jonliytalww6m25tzvqb6g2gcdtyud5tjzma,f019099,f05,0,8,bafkqae3gnfwc6mjpon2g64tbm5sw2ylsnnsxi,0,2640932,"{""DealIDs"":null,""SectorType"":3}",{}
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedz62madnpkah7ghnqpt7xds6ad7a5utj3vxmo2jco5jye5yy7lqo,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f04,f011206,0,12,bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza,0,503985558,"{""EventType"":1}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedz6jecxvukq4j74e46sbyjhrmfjxkz7t4oghiohgcuzxiu4b3p7e,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f019610,f04,0,4,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,77277838,"{""EventEpoch"":100359,""Payload"":""gQE=""}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedz7f5bragzkwz36zmnsntpqqbm4bpang2hvn62f42nvxvykl4qrs,bafy2bzaced4oqnb2gqwe45sutw4bksd25knwubhrrk4pzvwuhjhudp6xytexi,f02731,f05,0,8,bafkqae3gnfwc6mjpon2g64tbm5sw2ylsnnsxi,0,2645932,"{""DealIDs"":null,""SectorType"":3}",{}
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedz7fa2nspn36an3hnykrwiit7rorxkjnxpbvmhfkwcrljew5m5v6,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f04,f016356,0,12,bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza,0,227897962,"{""EventType"":1}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzalxkaivw5xr34eky7shujrbrw42yo37lfvmwujhfxsk6brkkqw,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f05728,f04,0,9,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,1335466654,,"{""PledgeCollateral"":{""Int"":8305121611547023530889461},""QualityAdjPower"":{""Int"":385958680480186368},""QualityAdjPowerSmoothed"":{""PositionEstimate"":{""Int"":131031567524352342715596315439041873899679366810938465141},""VelocityEstimate"":{""Int"":1338356856550395441892507665153955554806865091651389}},""RawBytePower"":{""Int"":385721185968586752}}"
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzcmvf3fyz2suoqosmrzhrzixxtjykuex43enccj5wdotckkmqfe,bafy2bzacedi46yoiiwcnbhyw56xmdnwyjclbqngoxzmuzzr5bq2soamma35qq,f02770,f05,0,8,bafkqae3gnfwc6mjpon2g64tbm5sw2ylsnnsxi,0,2719174,"{""DealIDs"":null,""SectorType"":3}",{}
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzcpj2nc6mbmuxzzabbho2igt3doz3prt7vywjivhhjbogj2mufu,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f04,f018235,0,12,bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza,0,1796729785,"{""EventType"":1}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzcvpcr6rhewepeljefhauah2p367jzpsnp4iirez7s6y3a57mbu,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f03079,f02,0,3,bafkqaddgnfwc6mjpojsxoylsmq,0,1105557904,,"{""ThisEpochBaselinePower"":{""Int"":2900910851306909927},""ThisEpochReward"":{""Int"":63652721713844685221},""ThisEpochRewardSmoothed"":{""PositionEstimate"":{""Int"":21637810881947330599433200029828978685045752880790941636015},""VelocityEstimate"":{""Int"":91555055095056965112527863752753533663925709816534258}}}"
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzei5ezoxgykp5rf2yxorwmgjyst2pi4abv5rtexdocetrcvqcne,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f012899,f04,0,9,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,579122908,,"{""PledgeCollateral"":{""Int"":8305121611547023530889461},""QualityAdjPower"":{""Int"":385958680480186368},""QualityAdjPowerSmoothed"":{""PositionEstimate"":{""Int"":131031567524352342715596315439041873899679366810938465141},""VelocityEstimate"":{""Int"":1338356856550395441892507665153955554806865091651389}},""RawBytePower"":{""Int"":385721185968586752}}"
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzfq453uvkxwx7ehe456cwb6qr63a4w4pbqa2jbnxehxrkqxtxxm,bafy2bzacec6pjilb5oht4cfemy272l6iiawmah3snoe2g5izo5dsschhealoe,f09696,f05,0,8,bafkqae3gnfwc6mjpon2g64tbm5sw2ylsnnsxi,0,2639932,"{""DealIDs"":null,""SectorType"":3}",{}
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzkypcgzfbvpjtmwequnk4dknrpwmezbjuaz6jnkueda7ugxjape,bafy2bzaceaf5hdtar7h7jszhrf2led5jcgxuqvk27ulc7bo7fuwrlliaq6lle,f020330,f02,0,3,bafkqaddgnfwc6mjpojsxoylsmq,0,385317,,"{""ThisEpochBaselinePower"":{""Int"":2900910851306909927},""ThisEpochReward"":{""Int"":63652721713844685221},""ThisEpochRewardSmoothed"":{""PositionEstimate"":{""Int"":21637810881947330599433200029828978685045752880790941636015},""VelocityEstimate"":{""Int"":91555055095056965112527863752753533663925709816534258}}}"
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzlk74p6uaj4e7jgv7kik37yniltvznwnupe3ofxe6mvul3ldt4s,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f04,f01235,0,17,bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza,0,2113005455,"{""Sectors"":[439433,439450,439436]}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzm527uwhcz3guppogbqijg3lcaccg6ggyrzkeo7li6mrdmgqahq,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f04,f04653,0,12,bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza,0,1059756180,"{""EventType"":1}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzszltxucuk44u6anq62bu7vl7ometttcrg4ujgsxswmf6vg32e6,bafy2bzacedjqokfhk266w6zapdoq35g274zbstvieupb6oow54m4jhrkuwfyc,f04,f021692,0,12,bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza,0,1804476539,"{""EventType"":1}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedztc6pelgitug77pduo5dqdx5t5urnvmzsi6s5hpetvb7d4ffjzo,bafy2bzacebjpactlxoon32qjuf3hty4vnrhtdlcnacmhmhbrdk72g2c45yfvq,f019099,f05,0,8,bafkqae3gnfwc6mjpon2g64tbm5sw2ylsnnsxi,0,2640932,"{""DealIDs"":null,""SectorType"":3}",{}
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedztrrpnew4yfy7gisoxl6yzhhce34wl5zn2kczsbmbpshicuod5s,bafy2bzacec5cqgikccwueg7oi4teewsyb25c5coppfjkoemeer7qjxygxylsa,f01272,f04,0,8,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,43575257,"{""DealIDs"":null,""InteractiveRandomness"":""H+oobMqRrUZiSrrhaHs9M6xg13KDFYc1J+KoxA72BKE="",""Proof"":""gCBCOI8Ris8w5x05llu155zSe9d2TcYjgq0odCbnXauEaLgJ1fM83prQnsOIUoBVuLg9SoNakybYKW6meNjdWtRx2aUsnH2XnLfcPGXRYOye1XATRY/Xzy/zK1YrHoUjDMkHZRSQwu19KIfIwtdgHndq/fcVtWKCSdm5Q21p61CSQ10otJbBV0spCgpu13b7mW/zv/Ee1kJeQorpgRnd8sL0QZcYfw3BsNyPjec+ArfswMdQoWnDO6bM5rlXQo7SiX+OWZsiaoXOvPPTXgIA2i59I2XBWf6Az6+AnSw6xCAG4zYR490oAv3Kvr8/EA4JglV6Q0GaBHXmDcO0SndkCWahZIHIhbO+QXWJYCJaPQNYUi/efu0woKj+FWUsKb+ICeHQYAZtWxFxmyarGw9Jop5VtfLRHZiQotQUhnKo0otXpk6i+96BsoGp7ZB9sSyUufuHJkplV7QsF/wiUa3bN4IX09kF3y8voNKlNEqQWesLA5ArmQNcf5vot2+ck9H/kbyobpotzEH5Psk57uzECq/d3o6J7fiR6Uwe9acAtr/9fDTUNLC/527HD/qarg1Tk7ToeoizIHQjc7LnLqHljArPPZt9xqc/P0MwE/akUBQACDL01tFhVZUpWl80fwMhGEUIdcma3nt9LWRwiOf7+6NyKCPfvRPcnGQKL/eO/CLruL/y18RS58Ws7B4moCQAgw5vjVK5ZUgjsZwTVdWWlDEpGDw0hrDoVwYnJZ+tR/eFQKsMYp9aAHoj5zqxNAfygCYkouznXCShWyUcMibExvRK85w7bsthbxVAjDbXwC8wnKnRNe3pETmOmINOss6xqr9en68AukB55DfC6Us+Uq+AOgeyhIMgDR2g7Cfn1QIEvqHkdq/jpP3zKUDq5+HnBCFESlozASe7IoY4PTJX+6rEgKKxB0n67RRdubuKd6Fn571lqlF4xDCum/5KjbOYhBMtFggwsWe8z8RrfRtO2v2g+BTbcVLHED9nTCT+5gHPUQnbPKV3keAZp1GIkBMrjVJi+aWTZ4syQbMPetGktUwMZkss3Wzo/RGv6I788BrXO+qLQaQM21U+O94cxBj1tm/YLmYuaS05bAW1ak4k+jzX5I7T474hs0Zb378xahcQ286OEJmVa0gVxvcvwV0tGcTY3nyUsJTabQC8UBjsCbFDvxWRiD52rlW7jbREwpD9aZjz48PlsW9Zeg8LY07Ep0kG28n4ZQ4x0ZVJSsxXz5KvhLZSqyCVLJh89PZIuA7SdZphA/Ku1EyucyChBUWboltbA4ih1BMBGNC2hGAyuwErUUBwYBRQGYOl3nQGZ0s2lqSUi+RIVT9ToYYjwasdqark8z4UaZ7hZFbph/m+4N9TPdW5LLsh0zqtQ/+9NAG2IKhD2FPNDuYtGies43f2GNZ+lLEY4EgmbOROlpTRodOlLX4JLzu4r1PV/puYKndKHK1DnmXz7wAIdtJ0dRG3o/yXVM1RxwgYtNovNrAGL+oZgkCkYcQX+/NaZ295zDD7GxsrkcBzCERUOJZ3UfReh/aJwcHB6BA3F5hDjFYsXjvHY4NoeHpPhHdsA4nkySy5+4+/AYUFgL2YKAdsm1Hkjl+o91Jsoro0hplIcKG+oJ03r4aqr36MsV2YZij2SV8tJG0Q99vpQuxIi8zXaj2hGEoLDbtCp4NVZI5W34ANsP8ZtcgOsx/aJ8gSlFqp7+MeDgkvZLKXl9VhpriR4cr/jHuNPRMgAzdtzaJtjiXDfMt67t8Aq5/hvIL6+yo4UZ9edvBpHlRo1mm37oD/9znJthpg3Y8YFmH4M7LkL2L1noxwrUcw7VaoMCITVMZGT0Xo/FtPBwhVBXRsOXTV+uSjiPpWoeiUhyiszWOMqKelMRfw2pgK0N32jgfSHX4NU4BPvvvy3m4HkOcRxd45PgDNDJdIZJWCknx/0h4Pg5JFsycl/xyaC4EfvgLngP9YEv9MSygWhuzMfA7TfHVkOCofrNSk5TflmVP+rSXb+r5DLHhcpZfkFUyrK84e18pzfcC4IWRiHwqb1bDFW4Z1cCeyrSr/ty7RLHhOaNTlk8f0S6Nrh1KzSPD9CYLzjfA0CRgWwMvLIZNLKjDXhH9dkJ4Jh7jumeYxjhU6wW/7SH+S/x5uyBTGr8+NP9/2CSmk41REDudt3zws/UnuJgggLr1qE7w+aZLRAV7QuGFqIE7gl2K39x2gNS75ygzTgILPimm6uf1yMzrQbLzfU9luB7aGgqhFRxwhhUWQxu9nhZJh8xrFbsqqlX0c7oGu/KQZhApB2EGjRxPmh35eEUksBLhop/4HauOyq3Qbyj0J3zb5GShPh09bgI2BBYExNfd7XysyjNoMR1VrI6zVbGrKliJLmDSPF/xNj45+k2eNsH8XS/XUcQk8Uwjp73dj6OoEnkCFfmajmvKAEwuHQFZEP1H2BtWlQFSAGeppgetFCNi2WzLTaWmiivgy684eQjzYq5UV0WLn4Jh0n/17YfcgMHWcjxH3SwDgUCVuh5qZcogEnajCTmg2QtyJ/HEffhMAriNm6XCNbXS+czFP9nSVQusP"",""Randomness"":""kS85r4u5RzTPctiaj6GMy3BcfpSTqnlJC3rjTGuRs/0="",""SealProof"":3,""SealedCID"":{""/"":""bagboea4b5abcbytekikfof4qpb6oifstiyt6b4bu55w33do52ys2osz55en34hlj""},""SectorID"":{""Miner"":1272,""Number"":824192},""UnsealedCID"":{""/"":""baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq""}}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzvh6sfjf2jkdjoieqql2oy4u4ayh3vxat36m2jvcbnfgez7un4o,bafy2bzaced4oqnb2gqwe45sutw4bksd25knwubhrrk4pzvwuhjhudp6xytexi,f02731,f04,0,8,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,50723015,"{""DealIDs"":null,""InteractiveRandomness"":""/xrLQxy1S/6MTCz81tSYDKBmssHcNOjqZfs4pEC2Y+Y="",""Proof"":""lRpnrPBRXzldwlUgxp5gHh5ZzOzT0DsB6WJAquKowndk2p/4nDFAyU+7cqZbHwoPmXUbBLFUwY1nHiavh4oMJo2zwWhAep6sXqw/LF98LJyaI0oMw5CYdiDxS7eagFOpEk8MClCtmZfbypvwgvqBgOBqXRlrbHAHHPRO7iG+TpeQ9EKqfphiMuuCUDyM4JifqONk9S81vZtp9H2N0CehGmAD6uOTjoEn70KTpmhnbsSAMAHCCcERLY9PqRMr/W0rsQBNbiWtWa9LR+VhzYeMKqeW/8EaWsetVN+/TQ2smZnxu0F+OoYxnd7IKBUWLXSTqe1Wv1f1qjnpXqsfGRXca9Whp2x0upQtTND02lGhw3doFlWIFRNE8KATsj9RpYLoFtSBYwcGon/ZvaYbohscCz/TL1h/CuUvvtK34WS3y+65qfwvPRhkHpx/RVI58ltdk4Z6AhbJxhTCAT1TliVZCSVbei2/pP/1lm2WgXQh9HHw4gzxW35eVsa3ixlfG6AapRhA76z8kBTAiJ1s6fGvyqpsrthbFOowON1QRtAJ/eCyT9iSBxYZae8cXfDpoYOIpMgv/BNYSn8wc4uE34hd98ySDPhyk2e92VwWsfbeBvPykuApzUbI/iuExxREYfmQDHEIac0I2HmVf5pGIsHgnvOFPJELLO+0RzWY/AFnAgf9T+SRnE/slB1Dvp4I/QxCil8rb8nPUp4QF0FU7UJJEJjVYIJ0/zXZDg4p72AGe8rWpbKD5UVQrVF0GCxcJD1BqJQNK8/6Ivcubt8kAB5XXp2UOGtQUx0uKMoK7of/xAT7GjCixNGHVUpU30fGgb3wucae9HcmcEVl7zrse0hm6qcNoSU4rVoXT5bfTrYpSIxye6H/80KpSNcDrqyXZ6VmB8gTtYbRrk7EKR3KWYLC228e2dGAvG21PIAScdBMEDe6HjJu6t5eNzcoQldhHElUp4x76AFzx0g/J7laECawx+8jQ70TY1c0wpmubPPDWvDVaXNiqAOhJTrKdV6lcbsNpbxY7eWxOG+Ih1kKF1Sy/yqlB6OMsu4e3SIsN63HBYnG6todxGKn0ZQSs+9eYxQWrLI5xe4dLpgXME8s26mKluN+ADBmvM0QO1Ffk1XXVyZIEbjl5T7MubR07IH+lY/WCcMbB4jaz8qA6qjrC8xRIJwY/Pme9skQ5Rr063QYws1EqC9a1A1I1xFSC/He1mp5gQBWtzMtt3JTuY21vSCWiuz0sKsyc8Dm98No/bJoWceI6SPuyNf4MSOzDRUIUZbjhV6C+EeBI3Ak2htdVKHgKK8gBevchFHcA/0fuvzhr/IBfzS2aTGprE9NPRzRNz51lK8jx8nB6845EPtux+tLdv7kPkKcRzsU1Ik7x1KpQ6842mkH3WcTmGUhNpK1GOvGE4vZbckEMI/VROjt9aVAybNO4UreLJ/fKA6cR+TCgs0qimya4geCsPi6b3q1IzjksP3FYctpjro3a0pe9oLcRD7KKgrkAfv3VDumNqmdra1jRxihkPbiL0KkZsVyZCTsuDTl/46+b6AWS6rA7GgaZLJR/xBayn9cJH4UZnErzV+m9gNEvqkN2eZ10X514YvjhWUgHJDnfZyoSSbXeYNEgeJnAkPlJNvxvKM32mi6Vun/KoyQYlQlr8742wnsksUcFha6JNdDIwW5CG3qC2dkNFWhiDhyfMuZFfZUmYrnm2BWiXTZVLbiWpllbv3WNm/Dk+y6jW8j48E9ComlYlkCjOmVZ3DzaHdr92nDoNhwV+X0ZHYj+sH8Mk8M32jEnVccrk6EyjKWNS/a34HhF2Ow0e3mqKMAvjOZ4zBJRp3mlTd8NnDkWU8PMN6FSLVEWWRqgf2W5JHAkUbkxKyKT2bzqPm0wOkfaVeGAp3IVrIGnuoW5rv/Lh320csFNuAqi96lC7jwbcckYEN9yDWN/XgC4hd8XPHl2+zA1LbK+7p29V0EbujE0TyyWcVTakOHzwRLiHoFLJHeCb1tADyj5USKs5HQFgmEtN2N1azzido1gtTabk5qDDQ73RJghoJZ+mgytnUEHAyP7q5ylSOYKuoCmWx4BLDoi5El8b10ELYUy/MgYA1qYWNwT8MvrF45aRbKkCJqrRbILUNGRjAs0V4N0vUoBRRUPqjldq14Rb9xACPpXvRg080tHCNiiKGrsBimA5Yc4aOEtRorkt5xm4gS5ydZ1m2hz2n0idUfOubcNVKU9KfD8llngkoVAratBTA3oJqHgrgyowo94ECjXDZnaUD1il269oNuESvCjNRg2lNzDQD2tOQ3mG8LgHgttPwjtk91MEBIwgQe9K+CYul1p5/AuXBF78goGW2tnssuGy2d+UOg0IExngbb1GRG5lgkoFi50YE1hNGD4BTt/SqixLRObK5UkEDIsKBB6uDuEbrTz6Jy1mfr3PXZd/rei2z7BCmr0pOgO/eDtxN5BJg/H6nBSKp3VFXRMFrX2VEsrf+7Z1xQxetiVitomRJcaUwLiJVhNCX9SURnLm0HN/qkAzi822Ix6UWB1oWCEplpGSx4ToXxqRPcXKH0YBdBJauh"",""Randomness"":""3Obs8DmUOBkyB0s0MPY3v/jAu37G1MhszvmHbadk0+M="",""SealProof"":3,""SealedCID"":{""/"":""bagboea4b5abcbn6ijfy3r5eldrmdgqjtma76kxvpovj65jz355uextqhmbroxulg""},""SectorID"":{""Miner"":2731,""Number"":217762},""UnsealedCID"":{""/"":""baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq""}}",
100299,bafy2bzacedrmbruuyltyesap455e53pkgn7ogatt2l5w5c7xirs4z7tjci3de,bafy2bzacedzvlkfa5p4bsh2duxmyyvjdfhy7o2ebv32fpbu6hmbci647ltk2w,bafy2bzacecznbl6c637wfj6pg74jl5qymor6vz3u5mwg23nnulgnjwzcyda6u,f020330,f04,0,9,bafkqaetgnfwc6mjpon2g64tbm5sxa33xmvza,0,484415,,"{""PledgeCollateral"":{""Int"":8305121611547023530889461},""QualityAdjPower"":{""Int"":385958680480186368},""QualityAdjPowerSmoothed"":{""PositionEstimate"":{""Int"":131031567524352342715596315439041873899679366810938465141},""VelocityEstimate"":{""Int"":1338356856550395441892507665153955554806865091651389}},""RawBytePower"":{""Int"":385721185968586752}}"
```

### PR DESCRIPTION
**Pull request by frrist**
- fixes #1106

### CODE REVIEW

File: schemas/v1/13_vm_messages_index.go [hunk 1]
```diff
@@ -0,0 +1,14 @@
+package v1
+
+func init() {
+	patches.Register(
+		13,
+		`
+ALTER TABLE {{ .SchemaName | default "public"}}.vm_messages
+    ADD COLUMN "index" BIGINT NOT NULL,
+    ADD CONSTRAINT vm_messages_uniq_index UNIQUE (height, state_root, cid, source, index);
```
Comment (davidgasquez) [inline schemas/v1/13_vm_messages_index.go:9]: We can enforce/check this in the final dataset. :)

**Review by birdychang — APPROVED** [review]

**Review by kasteph — APPROVED** [review]
