### PR TITLE
fix: track dealID's of snapped sector

### LINKED ISSUE #900: Track dealID's of snapped sectors in MinerSectorDeals model
### Describe the bug:
Snapped sectors will contain dealID's, currently we don't track these

### Lily Version: v0.8.7

### PR DESCRIPTION
**Pull request by frrist**
- fixes #900

### CODE REVIEW

File: tasks/actorstate/miner.go [hunk 1]
```diff
@@ -385,6 +385,16 @@ func ExtractMinerSectorData(ctx context.Context, ec *MinerStateExtractionContext
...
+		for _, snappedSector := range sectorChanges.Snapped {
+			for _, dealID := range snappedSector.To.DealIDs {
+				sectorDealsModel = append(sectorDealsModel, &minermodel.MinerSectorDeal{
+					Height:   int64(ec.CurrTs.Height()),
+					MinerID:  a.Address.String(),
+					SectorID: uint64(snappedSector.To.SectorNumber),
+					DealID:   uint64(dealID),
+				})
+			}
+		}
```
Comment (placer14) [inline tasks/actorstate/miner.go:397]: I assume this means we're missing data in production? Am I correct in thinking we can just re-walk the epochs since the v15 upgrade?

**Review by placer14 — APPROVED** [review]

File: tasks/actorstate/miner.go (hunk 1 above)
Comment (frrist) [reply tasks/actorstate/miner.go:397]: Sadly yes, and thankfully yes. --from=`1594679` --to=`current_height`

**Comment by frrist** [comment]
@iand if you can give this a look in your AM and it looks good please merge it, I'll cut a release when I wake up and we'll get this deployed and pushed out to users.

**Review by iand — APPROVED** [review]
