### PR TITLE
fix: loading miner actor when actor doesn't exist

### LINKED ISSUE #897: [Indexer Refactor] miner_pre_commit_infos, miner_sector_infos, miner_sector_deals, and miner_sector_events task failures
### Describe the bug:
miner_* extractor tasks failed with error:
```
+-------+--------------------------------------------------------------+----------+----------------------+---------------------------------+---------------------------------+------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|height |state_root                                                    |reporter  |task                  |started_at                       |completed_at                     |status|status_information|errors_detected                                                                                                                                                                                                                                      |
+-------+--------------------------------------------------------------+----------+----------------------+---------------------------------+---------------------------------+------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|1597922|bafy2bzacebbquiigcrkxbibhvutzrnw467tt6rukehyhragugbcuvz6s4ipme|REDIS_TEST|miner_pre_commit_infos|2022-03-02 18:02:00.556979 +00:00|2022-03-02 18:02:09.827997 +00:00|ERROR |NULL              |[{"Code": "bafkqaetgnfwc6nzpon2g64tbm5sw22lomvza", "Head": "bafy2bzaced3zgttglajio6s66zrzbsovgrxf4cbcnz4qgqi7762ty3qknt63q", "Name": "fil/7/storageminer", "Error": "failed to extract parsed actor state: actor not found", "Address": "f01761836"}]|
|1597922|bafy2bzacebbquiigcrkxbibhvutzrnw467tt6rukehyhragugbcuvz6s4ipme|REDIS_TEST|miner_sector_infos    |2022-03-02 18:02:00.556979 +00:00|2022-03-02 18:02:34.340599 +00:00|ERROR |NULL              |[{"Code": "bafkqaetgnfwc6nzpon2g64tbm5sw22lomvza", "Head": "bafy2bzaced3zgttglajio6s66zrzbsovgrxf4cbcnz4qgqi7762ty3qknt63q", "Name": "fil/7/storageminer", "Error": "failed to extract parsed actor state: actor not found", "Address": "f01761836"}]|
|1597922|bafy2bzacebbquiigcrkxbibhvutzrnw467tt6rukehyhragugbcuvz6s4ipme|REDIS_TEST|miner_sector_deals    |2022-03-02 18:02:00.556979 +00:00|2022-03-02 18:02:34.340621 +00:00|ERROR |NULL              |[{"Code": "bafkqaetgnfwc6nzpon2g64tbm5sw22lomvza", "Head": "bafy2bzaced3zgttglajio6s66zrzbsovgrxf4cbcnz4qgqi7762ty3qknt63q", "Name": "fil/7/storageminer", "Error": "failed to extract parsed actor state: actor not found", "Address": "f01761836"}]|
|1597922|bafy2bzacebbquiigcrkxbibhvutzrnw467tt6rukehyhragugbcuvz6s4ipme|REDIS_TEST|miner_sector_events   |2022-03-02 18:02:00.556979 +00:00|2022-03-02 18:02:34.342366 +00:00|ERROR |NULL              |[{"Code": "bafkqaetgnfwc6nzpon2g64tbm5sw22lomvza", "Head": "bafy2bzaced3zgttglajio6s66zrzbsovgrxf4cbcnz4qgqi7762ty3qknt63q", "Name": "fil/7/storageminer", "Error": "failed to extract parsed actor state: actor not found", "Address": "f01761836"}]|
+-------+--------------------------------------------------------------+----------+----------------------+---------------------------------+---------------------------------+------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

### Steps to Reproduce:
Run walk, watch, or index with `miner_pre_commit_infos, miner_sector_infos, miner_sector_deals, and miner_sector_events` enabled.

### Lily Version: `indexer-refactor` branch

### PR DESCRIPTION
**Pull request by frrist**
Note: This PR targets indexer-refactor branch
- fixes #897
- simply miner extractor logic
- ensure snapped sector dealID's are recorded by SectorDealsExtractor

### CODE REVIEW

File: chain/actors/builtin/miner/diff.go [hunk 1]
```diff
@@ -80,9 +80,25 @@ func DiffPreCommits(ctx context.Context, store adt.Store, pre, cur State) (*PreC
...
+	return out
+}
+
+func MakePreCommitChanges() *PreCommitChanges {
+	var out *PreCommitChanges
+	out.Added = []SectorPreCommitOnChainInfo{}
+	out.Removed = []SectorPreCommitOnChainInfo{}
+	return out
+}
+
```
Comment (frrist) [inline chain/actors/builtin/miner/diff.go:98]: Ensure structure containing diff doesn't have `nil` fields

**Review by iand — APPROVED** [review]
