### PR TITLE
fix: avoid custom marshal for zero and invalid values

### LINKED ISSUE #892: Message Param Parsing fails due to zero value
### Describe the bug:
```
[
{"Cid": {"/": "bafy2bzaceahzeoc3svzoe6aa7j2m5p6o2c5kmjxhoo25gajinxz2f25i6q4kw"}, "Error": "failed to parse message params: failed to parse message params method: 2, actor code: bafkqafdgnfwc6nrpobqxs3lfnz2gg2dbnzxgk3a, params: ��U\u0002\u0001�\"�\u001a�#\u0005t�`�\":�d_z�Q\\u0000\\u0000@�\u0006\u0018WF\\u0000\u0001�v��\\u0000�Xa\u0002�oUp�ٮ}�2@��\u000b\u000fI\u0015��enw�\u0011GYWI\u001b\f�wӱ'�����<KM�\u0014$�\u001f\u0011�s�;����J��\u001d�[��G)<=��n��eIH$�Tׁ��[R\u0001,q�|d���,@: failed to override message param json marshaller: reflect: call of reflect.Value.IsZero on zero Value"}, 
{"Cid": {"/": "bafy2bzaceban4nrhvv6icllbfvks6vejpm3g57qx3h52tpg7mxgwpaf2ybz6a"}, "Error": "failed to parse message params: failed to parse message params method: 2, actor code: bafkqafdgnfwc6nrpobqxs3lfnz2gg2dbnzxgk3a, params: ��U\u0002\u0001�\"�\u001a�#\u0005t�`�\":�d_z�Q\\u0000\\u0000@�\u0007\u0018WF\\u0000\u0001�v��\\u0000�Xa\u0002��埤\u001a1�P(�z��*�~�ߩ��b\u0016\u000b)�����\\u0000��K!�\\< \u0013�11�i�\\u0000Q��\u001a��3��0�\"\t���\u0018\u0004ᎀs�v�|'�!�l乶����\t�\u0019���R��@: failed to override message param json marshaller: reflect: call of reflect.Value.IsZero on zero Value"},
{"Cid": {"/": "bafy2bzaced6ra72qcfue44qmrumjslhrxolzenbfub5nz6w6rt4pabkvarobi"}, "Error": "failed to parse message params: failed to parse message params method: 2, actor code: bafkqafdgnfwc6nrpobqxs3lfnz2gg2dbnzxgk3a, params: ��U\u0002\u0001�\"�\u001a�#\u0005t�`�\":�d_z�Q\\u0000\\u0000@�\\u0000\u0002D\\u0000C! \\u0000�Xa\u0002�u�u�\r<��2b_Z�D=eΝ������lKFj��\u001c�}�&�;g\u0004��v�����\r-��o�\fA�u�c\u0018q��V���c�Q�����\u000b������\u0002n$+\u0004w�\n8g�V@: failed to override message param json marshaller: reflect: call of reflect.Value.IsZero on zero Value"},
{"Cid": {"/": "bafy2bzacecovzurhi4h6ti6cr6aqns3y3u3mswtjyk5jxeass7xetxgzxmvsq"}, "Error": "failed to parse message params: failed to parse message params method: 2, actor code: bafkqafdgnfwc6nrpobqxs3lfnz2gg2dbnzxgk3a, params: ��U\u0002\u0001�\"�\u001a�#\u0005t�`�\":�d_z�Q\\u0000\\u0000@�\u0001\u0002D\\u0000BG@\\u0000�Xa\u0002�j>q�#�n�\u0006q����Y|[�D\u000b��و&}��ʔ-m\u0019��1��/ �-�L@��\u0007;���\u001c�ϐ��k�cB�0�.Q�G��X�t\u000bkV\u001b���]\"�\u001d����\u0013W�@: failed to override message param json marshaller: reflect: call of reflect.Value.IsZero on zero Value"}, 
{"Cid": {"/": "bafy2bzaceaprkk4eub6gnxqium4wcjk5o675gwfgdzxm7by33zkheusmadi2a"}, "Error": "failed to parse message params: failed to parse message params method: 2, actor code: bafkqafdgnfwc6nrpobqxs3lfnz2gg2dbnzxgk3a, params: ��U\u0002\u0001�\"�\u001a�#\u0005t�`�\":�d_z�Q\\u0000\\u0000@�\u0002\u0018>E\\u0000�\u001a\u0003�\\u0000�Xa\u0002�'0\"\u001a�[R�B<�V\u001d\u0018H�\u001cFE\r:��q}���\u0017F�Y��\u001d\u0017Հ�40�\tH��Z\u0016;�M�qf���%��\u000b��Q�\\u0000o��'�c9��ҵq�ӳ��T�a\b��51/�49@: failed to override message param json marshaller: reflect: call of reflect.Value.IsZero on zero Value"},
{"Cid": {"/": "bafy2bzacebrh4pe2apyid7rs64gn7minhv5jcsbuouovnza6ythsgq7cse2j2"}, "Error": "failed to parse message params: failed to parse message params method: 2, actor code: bafkqafdgnfwc6nrpobqxs3lfnz2gg2dbnzxgk3a, params: ��U\u0002\u0001�\"�\u001a�#\u0005t�`�\":�d_z�Q\\u0000\\u0000@�\u0003\u0018>E\\u0000�\\��\\u0000�Xa\u0002�#u%�02\rP\u001eB�]@\u0003(�P�������\u0005\f�fU=J� ��\u001c\u001f�7�N\u00196}Y\u0011�\u0011�2\u000es@\u0018�\u000bW�ƞ��Z1cvώPzX��t��\f\u0014�u�\u001a���\u0007�w9Sw�{U�@: failed to override message param json marshaller: reflect: call of reflect.Value.IsZero on zero Value"},
{"Cid": {"/": "bafy2bzacebebz6acyuaaqt2dd34pgusriluvmz76523e7pvarbcc57lwjkar4"}, "Error": "failed to parse message params: failed to parse message params method: 2, actor code: bafkqafdgnfwc6nrpobqxs3lfnz2gg2dbnzxgk3a, params: ��U\u0002\u0001�\"�\u001a�#\u0005t�`�\":�d_z�Q\\u0000\\u0000@�\u0004\u0018kF\\u0000\u0002ǐ�<\\u0000�Xa\u0002�}\u001b�VN'1\"pA#�%W<�jI nym[!P�Yv�#{���#�}�#�ͭ�!�g�\nO��sZ:�9M|uY�H��8�R�l���\u0016WY`57<��c�lLC2�ǵ��/��@: failed to override message param json marshaller: reflect: call of reflect.Value.IsZero on zero Value"},
{"Cid": {"/": "bafy2bzacea536daac45rlgnlm6v2gmao7aesrvwv5pvyzkxrk7ayx7jajzvy6"}, "Error": "failed to parse message params: failed to parse message params method: 2, actor code: bafkqafdgnfwc6nrpobqxs3lfnz2gg2dbnzxgk3a, params: ��U\u0002\u0001�\"�\u001a�#\u0005t�`�\":�d_z�Q\\u0000\\u0000@�\u0005\u0018WF\\u0000\u0001�v��\\u0000�Xa\u0002���;��!\u0016c\u0004�\u0017#I�\n?\u001e���s�\tD����\u0017VVq<�j��͡\u0013G=��G�6\u0012\u0011�]\u0001�\u0004)yK\"�G|�\u0010\\u0000w\u0012���>\t�\u0001%@����r\u001cV~\u0010�M�\u0010!k��*�@: failed to override message param json marshaller: reflect: call of reflect.Value.IsZero on zero Value"}]
```
reflect.Value.IsZero on zero Value

### Steps to Reproduce:
On calibnet run:
`lily walk --tasks=messages --from=435324 --to=435328`

### Lily Version: master

### PR DESCRIPTION
**Pull request by frrist**
- fixes #892

parsed_messages after apply this fix:
```
+--------------------------------------------------------------+------+--------------------------------------------------------------------------------------+-----------------------------------------+-----+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|cid                                                           |height|from                                                                                  |to                                       |value|method            |params                                                                                                                                                                                                                                                                                                                                                                                                                              |
+--------------------------------------------------------------+------+--------------------------------------------------------------------------------------+-----------------------------------------+-----+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|bafy2bzacebrh4pe2apyid7rs64gn7minhv5jcsbuouovnza6ythsgq7cse2j2|435326|t3tbpxmkoleewaphwounptqe2ypfz75pg2zxugk7zfyseggrxhggm242bybeywtszezruyc4anzaicahy2c55q|t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky|0    |UpdateChannelState|{"Sv": {"Lane": 3, "Extra": null, "Nonce": 62, "Amount": {"Int": 3982288084}, "Merges": null, "Signature": {"Data": "lyN1JbMwMg1QHkKtXUADKIhQwY27k4mMgAUMr2ZVPUq4IMbXHB+nN/JOGTZ9WRHLEe0yDnNAGOgLV8/GnsP8WjFjds+OUHpYhsh0hJoMFPF1rhru4uwHwXc5U3fDe1Wk", "Type": 2}, "ChannelAddr": "t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky", "TimeLockMax": 0, "TimeLockMin": 0, "SecretPreimage": null, "MinSettleHeight": 0}, "Secret": null}  |
|bafy2bzacebebz6acyuaaqt2dd34pgusriluvmz76523e7pvarbcc57lwjkar4|435326|t3tbpxmkoleewaphwounptqe2ypfz75pg2zxugk7zfyseggrxhggm242bybeywtszezruyc4anzaicahy2c55q|t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky|0    |UpdateChannelState|{"Sv": {"Lane": 4, "Extra": null, "Nonce": 107, "Amount": {"Int": 11938098236}, "Merges": null, "Signature": {"Data": "rH0bqFZOJzEicEEjqCVXPN9qSSBueW1bIVDMWXbHI3uHrIIj832FI8vNrfch1GfYCk+9pXNaOoM5TXx1WeJIudk4p1K9bOKyxhZXWWA1Nzy5sGPzbExDMpvHtf+CL4Gr", "Type": 2}, "ChannelAddr": "t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky", "TimeLockMax": 0, "TimeLockMin": 0, "SecretPreimage": null, "MinSettleHeight": 0}, "Secret": null}|
|bafy2bzacea536daac45rlgnlm6v2gmao7aesrvwv5pvyzkxrk7ayx7jajzvy6|435326|t3tbpxmkoleewaphwounptqe2ypfz75pg2zxugk7zfyseggrxhggm242bybeywtszezruyc4anzaicahy2c55q|t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky|0    |UpdateChannelState|{"Sv": {"Lane": 5, "Extra": null, "Nonce": 87, "Amount": {"Int": 7960172680}, "Merges": null, "Signature": {"Data": "laXIO/WJIRZjBLMXI0mtCj8ehLrAc6AJRPiDrM8XVlZxPNRqt4rNoRNHPYaYR+U2EhG9XQH6BCl5SyKjR3yaEAB3En/5qe8+CaIBJUC2jqqschxWfhDxTbcQIWuJ5yqM", "Type": 2}, "ChannelAddr": "t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky", "TimeLockMax": 0, "TimeLockMin": 0, "SecretPreimage": null, "MinSettleHeight": 0}, "Secret": null}  |
|bafy2bzaceaprkk4eub6gnxqium4wcjk5o675gwfgdzxm7by33zkheusmadi2a|435326|t3tbpxmkoleewaphwounptqe2ypfz75pg2zxugk7zfyseggrxhggm242bybeywtszezruyc4anzaicahy2c55q|t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky|0    |UpdateChannelState|{"Sv": {"Lane": 2, "Extra": null, "Nonce": 62, "Amount": {"Int": 3977905096}, "Merges": null, "Signature": {"Data": "jycwIhq3W1LsQjy9Vh0YSIAcRkUNOuzRcX3/hbIXRqVZt+kdF9WAzTQw7glInNVaFjvZTblxZruMpyWk7Au3zFHMAG+Y0yecYznp2NK1caLTs6ejVMBhCJylNTEv7TQ5", "Type": 2}, "ChannelAddr": "t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky", "TimeLockMax": 0, "TimeLockMin": 0, "SecretPreimage": null, "MinSettleHeight": 0}, "Secret": null}  |
|bafy2bzacecovzurhi4h6ti6cr6aqns3y3u3mswtjyk5jxeass7xetxgzxmvsq|435326|t3tbpxmkoleewaphwounptqe2ypfz75pg2zxugk7zfyseggrxhggm242bybeywtszezruyc4anzaicahy2c55q|t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky|0    |UpdateChannelState|{"Sv": {"Lane": 1, "Extra": null, "Nonce": 2, "Amount": {"Int": 4343616}, "Merges": null, "Signature": {"Data": "rGo+cY4jym6PBnHp9Mj8WXxb60QLkOjZiCZ9pKjKlC1tGZysMYz7LyC8LcxMQLmvBzuNiPMcoM+QmdtrqGNCwTDaLlHNR+WtWKR0fwtrVhvCmKzru10inx2S5eyeE1fr", "Type": 2}, "ChannelAddr": "t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky", "TimeLockMax": 0, "TimeLockMin": 0, "SecretPreimage": null, "MinSettleHeight": 0}, "Secret": null}      |
|bafy2bzaced6ra72qcfue44qmrumjslhrxolzenbfub5nz6w6rt4pabkvarobi|435326|t3tbpxmkoleewaphwounptqe2ypfz75pg2zxugk7zfyseggrxhggm242bybeywtszezruyc4anzaicahy2c55q|t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky|0    |UpdateChannelState|{"Sv": {"Lane": 0, "Extra": null, "Nonce": 2, "Amount": {"Int": 4399392}, "Merges": null, "Signature": {"Data": "kXWudf8NPL74MmJfWpdEPWXOne/F1v6L9mxLRmqGrxyJfcEmkDtnBP/kdoa0/fmQDS3x6m/xDEGGdY1jGHGju1b34thjpVH25MP2f48Lrr/n4/vMAm4kKwR3mAo4Z4RW", "Type": 2}, "ChannelAddr": "t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky", "TimeLockMax": 0, "TimeLockMin": 0, "SecretPreimage": null, "MinSettleHeight": 0}, "Secret": null}      |
|bafy2bzaceban4nrhvv6icllbfvks6vejpm3g57qx3h52tpg7mxgwpaf2ybz6a|435326|t3tbpxmkoleewaphwounptqe2ypfz75pg2zxugk7zfyseggrxhggm242bybeywtszezruyc4anzaicahy2c55q|t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky|0    |UpdateChannelState|{"Sv": {"Lane": 7, "Extra": null, "Nonce": 87, "Amount": {"Int": 7960172680}, "Merges": null, "Signature": {"Data": "iJ3ln6QaMb5QKK16oNMq5X6f36l/651iFgspysb0jKEAjJpLIe5cPCAT2zEx4WmqAFGVkhrgiTOg1jDJIgnh+OgYBOGOgHO6doV8J8whg2zkubaYlsLICdcZjpyGUvq9", "Type": 2}, "ChannelAddr": "t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky", "TimeLockMax": 0, "TimeLockMin": 0, "SecretPreimage": null, "MinSettleHeight": 0}, "Secret": null}  |
|bafy2bzaceahzeoc3svzoe6aa7j2m5p6o2c5kmjxhoo25gajinxz2f25i6q4kw|435326|t3tbpxmkoleewaphwounptqe2ypfz75pg2zxugk7zfyseggrxhggm242bybeywtszezruyc4anzaicahy2c55q|t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky|0    |UpdateChannelState|{"Sv": {"Lane": 6, "Extra": null, "Nonce": 87, "Amount": {"Int": 7960172680}, "Merges": null, "Signature": {"Data": "rm9VcNjZrn2MMkCMsQsPSRWjtmVud+ARR1lXSRsM13fTsSeeuoaImDxLTc4UJMwfEZFz/TuunrzhSqiKHfVbq5RHKTw9g4ZusbNlSUgk5VTXgfiIW1IBLHG1fGSqopUs", "Type": 2}, "ChannelAddr": "t2agxsfeq274rqk5f2mduseovdmrpxv52r6gp4mky", "TimeLockMax": 0, "TimeLockMin": 0, "SecretPreimage": null, "MinSettleHeight": 0}, "Secret": null}  |
+--------------------------------------------------------------+------+--------------------------------------------------------------------------------------+-----------------------------------------+-----+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### CODE REVIEW

**Review by iand — APPROVED** [review]

File: tasks/messages/message_test.go [hunk 1]
```diff
@@ -233,6 +238,34 @@ func TestParseMessageParams(t *testing.T) {
 			wantEncoded: "{\"Recoveries\":[{\"Deadline\":1,\"Partition\":1,\"Sectors\":{\"Count\":10,\"RLE\":[1,10]}}]}",
 			wantErr:     false,
 		},
+		// from https://github.com/filecoin-project/lily/issues/892
```
Comment (frrist) [inline tasks/messages/message_test.go:241]: without 691f5c2e39d850695a14c3cfd20d6a26cde9cf00 I have verified this test fails with:
```
message_test.go:292: got unexpected error: failed to parse message params method: 2, actor code: bafkqafdgnfwc6nrpobqxs3lfnz2gg2dbnzxgk3a, params: ��U�"��#t�`�":�d_z�Q@�WF�v���Xa�oUp�ٮ}�2@��I��enw�GYWI�wӱ'�����<KM�$��s�;����J���[��G)<=��n��eIH$�Tׁ��[R,q�|d���,@: failed to override message param json marshaller: reflect: call of reflect.Value.NumField on zero Value
```
